# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "bin/loom_backrun", "bin/keys", "bin/loom_anvil", "bin/gasbench", "bin/nodebench", "bin/replayer", "bin/loom_exex",
    "crates/defi-abi", "crates/defi-actors", "crates/defi-entities", "crates/defi-events", "crates/defi-pools",
    "crates/multicaller", "crates/topology", "crates/types", "crates/utils", "crates/flashbots", "crates/debug-provider", "crates/defi-blockchain",
    "crates/loom-revm-db", "bin/exex_grpc_loom", "crates/loom", "crates/uniswap-v3-math", "crates/uniswapx-actor-rs"]
default-members = ["bin/loom_backrun", "bin/keys", "bin/loom_anvil", "bin/gasbench", "bin/nodebench", "bin/replayer", "bin/loom_exex"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.79"
license = "MIT OR Apache-2.0"
homepage = ""
repository = ""
exclude = [".github/"]

[workspace.dependencies]
loom = { path = "crates/loom" }
loom-actors = { path = "crates/actors" }
loom-actors-macros = { path = "crates/actors-macros" }
loom-utils = { path = "crates/utils" }
loom-multicaller = { path = "crates/multicaller" }
loom-topology = { path = "crates/topology" }
loom-revm-db = { path = "crates/loom-revm-db" }
defi-types = { path = "crates/types" }
defi-actors = { path = "crates/defi-actors" }
defi-entities = { path = "crates/defi-entities" }
defi-pools = { path = "crates/defi-pools" }
defi-abi = { path = "crates/defi-abi" }
defi-events = { path = "crates/defi-events" }
defi-blockchain = { path = "crates/defi-blockchain" }
flashbots = { path = "crates/flashbots" }
debug-provider = { path = "crates/debug-provider" }
uniswap_v3_math = { path = "crates/uniswap-v3-math" }

tokio = { version = "1.37.0", features = ["full"] }
tokio-stream = "0.1.15"
tonic = "0.12"
eyre = "0.6.12"
env_logger = "0.11.1"
log = "0.4.19"
chrono = "0.4.26"
rayon = "1.8.1"
serde = "1.0.203"
serde_json = "1.0.119"
lazy_static = "1.4.0"
futures = "0.3.30"
futures-util = "0.3.30"
rand = "0.8.5"
num_cpus = "1.16.0"
async-trait = "0.1.80"
hex = "0.4.3"
sha2 = "0.10.7"
aes = "0.8.3"
toml = "^0.8.12"
url = "2.4.1"
reqwest = { version = "0.12.4", features = ["trust-dns", "json"] }
clap = { version = "4.5.4", features = ["derive"] }
strum = { version = "0.26.2" }
strum_macros = { version = "0.26.2" }
k256 = "0.13.3"
thiserror = "^1.0.61"
colored = "2.0.4"
indexmap = "2.5.0"

revm = { version = "14.0.1", features = [
    "std",
    "secp256k1",
    "blst",
], default-features = false }
revm-primitives = { version = "9.0.1", features = [
    "std",
], default-features = false }
revm-inspectors = "0.7"

alloy-core = "0.8.3"
alloy-chains = "0.1.30"
alloy-primitives = { version = "0.8.3", features = ["rand"] }
alloy-dyn-abi = { version = "0.8.3", features = ["json", "std"] }
alloy-sol-types = { version = "0.8.3", features = ["json"] }
alloy-sol-macro = { version = "0.8.3", features = ["json"] }

alloy-rlp = "0.3.8"
alloy-trie = "0.5"

alloy = { version = "0.3.3", features = ["full", "serde", "consensus", "node-bindings", "rpc-types-anvil", "rpc-types-trace", "json-rpc", "rpc-types-json", "rand", "rlp"] }

alloy-serde = "0.3.3"
alloy-contract = "0.3.3"
alloy-consensus = "0.3.3"
alloy-eips = "0.3.3"
alloy-provider = { version = "0.3.3", features = ["reqwest", "pubsub", "ws", "ipc", "debug-api", "anvil-node", "anvil-api"] }
alloy-json-rpc = "0.3.3"
alloy-network = "0.3.3"
alloy-node-bindings = "0.3.3"
alloy-rpc-client = { version = "0.3.3", features = ["pubsub", "ipc", "ws", "reqwest"] }
alloy-rpc-types = "0.3.3"
alloy-rpc-types-eth = "0.3.3"
alloy-rpc-types-anvil = "0.3.3"
alloy-rpc-types-beacon = "0.3.3"
alloy-rpc-types-trace = "0.3.3"
alloy-rpc-types-engine = "0.3.3"
alloy-transport = "0.3.3"
alloy-transport-ipc = "0.3.3"
alloy-transport-ws = "0.3.3"
alloy-transport-http = "0.3.3"
alloy-pubsub = "0.3.3"
alloy-signer = "0.3.3"
alloy-signer-local = "0.3.3"

reth = { git = "https://github.com/paradigmxyz/reth" }
reth-db = { git = "https://github.com/paradigmxyz/reth" }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth" }
reth-provider = { git = "https://github.com/paradigmxyz/reth" }
reth-rpc-types = { git = "https://github.com/paradigmxyz/reth" }
reth-rpc-types-compat = { git = "https://github.com/paradigmxyz/reth" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth" }
reth-exex = { git = "https://github.com/paradigmxyz/reth", features = ["serde"] }
reth-execution-types = { git = "https://github.com/paradigmxyz/reth" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth" }
reth-node-types = { git = "https://github.com/paradigmxyz/reth" }
reth-exex-test-utils = { git = "https://github.com/paradigmxyz/reth" }
reth-testing-utils = { git = "https://github.com/paradigmxyz/reth" }
reth-codecs = { git = "https://github.com/paradigmxyz/reth" }
reth-codecs-derive = { git = "https://github.com/paradigmxyz/reth" }
reth-ethereum-forks = { git = "https://github.com/paradigmxyz/reth" }


example-exex-remote = { git = "https://github.com/dexloom/reth-exex-grpc" }
#example-exex-remote = { path = "../reth-exex-grpc" }

tower = "0.5.1"

criterion = { version = "0.5.1", features = ["async_tokio"] }
uniswapx-client-rs = { git = "https://github.com/cakevm/uniswapx-client-rs", rev="29b2b2c" }