[package]
name = "loom-defi-custom-pools"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
loom-defi-pools.workspace = true
loom-evm-db.workspace = true
loom-types-entities.workspace = true

alloy-primitives.workspace = true
enum_delegate.workspace = true
eyre.workspace = true
revm.workspace = true
